version: '3'
services:
  mysql:
    image: mysql:8.0.33
    container_name: school.db
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=SchoolDB
    ports:
      - "3306:3306"
    networks:
      - my_network

  app:
    image: app_for_db
    container_name: school.app
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mysql
    networks:
      - my_network

networks:
  my_network:
    driver: bridge